model:
  base_learning_rate: 4.5e-6
  target: DAEFR.models.vqgan_dual.DAEFRModel
  params:
    image_key: 'lq'
    # HQ codebook path
    ckpt_path_HQ: '/ssd1/yuju/DAEFR/experiments/HQ_codebook/HQ_codebook.ckpt'
    # LQ codebook path
    ckpt_path_LQ: '/ssd1/yuju/DAEFR/experiments/logs/2023-09-04T23-09-24_LQ_Dictionary_new_range/checkpoints/epoch=000241-Rec_loss=0.02687305212020874-Codebook_loss=0.019417351111769676.ckpt'
    encoder_codebook_type: 'LQHQ'
    schedule_step: [4000000, 8000000]
    ddconfig:
      target: DAEFR.modules.vqvae.vqvae_arch.VQVAEGAN
      params:
        embed_dim: 256
        n_embed: 1024
        double_z: False
        z_channels: 256
        resolution: 512
        in_channels: 3
        out_ch: 3
        ch: 64
        ch_mult: [ 1,2,2,4,4,8]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        attn_resolutions: [16]
        dropout: 0.0
        enable_mid: True
        fix_decoder: False
        fix_codebook: False

    lossconfig:
      target: DAEFR.modules.losses.vqperceptual_dual.VQLPIPSWithDiscriminatorWithCompWithIdentity
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 11
        disc_weight: 0.8
        codebook_weight: 1.0
        use_actnorm: False

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: DAEFR.data.ffhq_degradation_dataset.FFHQDegradationDataset
      params:
        dataroot_gt: /ssd1/yuju/dataset/FFHQ/images512x512
        io_backend:
          type: disk
        use_hflip: True
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
        out_size: 512

        # large range
        blur_kernel_size: [19,20]
        kernel_list: ['iso', 'aniso']
        kernel_prob: [0.5, 0.5]
        blur_sigma: [0.1, 15]
        downsample_range: [0.8, 30]
        noise_range: [0, 20]
        jpeg_range: [30, 100]

        color_jitter_prob: ~
        color_jitter_shift: 20
        color_jitter_pt_prob: ~
        gray_prob: ~
        gt_gray: True

        crop_components: True
        component_path: experiments/pretrained_models/FFHQ_eye_mouth_landmarks_512.pth
        eye_enlarge_ratio: 1.4


    validation:
      target: DAEFR.data.ffhq_degradation_dataset.FFHQDegradationDataset
      params:
        dataroot_gt: /ssd1/yuju/dataset/FFHQ/images512x512_validation
        io_backend:
          type: disk
        use_hflip: False
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
        out_size: 512

        # original
        # blur_kernel_size: [19,20]
        # kernel_list: ['iso', 'aniso']
        # kernel_prob: [0.5, 0.5]
        # blur_sigma: [0.1, 10]
        # downsample_range: [0.8, 8]
        # noise_range: [0, 20]
        # jpeg_range: [60, 100]

        # large range
        blur_kernel_size: [19,20]
        kernel_list: ['iso', 'aniso']
        kernel_prob: [0.5, 0.5]
        blur_sigma: [0.1, 15]
        downsample_range: [0.8, 30]
        noise_range: [0, 20]
        jpeg_range: [30, 100]

        # color jitter and gray
        color_jitter_prob: ~
        color_jitter_shift: 20
        color_jitter_pt_prob: ~
        gray_prob: ~
        gt_gray: True

        crop_components: False
        component_path: experiments/pretrained_models/FFHQ_eye_mouth_landmarks_512.pth
        eye_enlarge_ratio: 1.4